project 'redpine.xcodeproj'

target 'redpine' do
  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'

  pod 'RNDeviceInfo', :path => '../node_modules/react-native-device-info'
  pod 'yoga', path: '../node_modules/react-native/ReactCommon/yoga'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
  pod 'React', path: '../node_modules/react-native', subspecs: [
    'Core',
    'cxxreact',
    'CxxBridge',
    'DevSupport',
    'RCTText',
    'RCTImage',
    'RCTNetwork',
    'RCTActionSheet',
    'RCTAnimation',
    'RCTWebSocket',
    'RCTPushNotification',
  ]

  pod 'RNSquarePos', :path => '../node_modules/react-native-square-pos'
  pod 'Firebase/Core'
  pod 'Firebase/Messaging'

  pod 'RNScreens', :path => '../node_modules/react-native-screens'


  pod 'react-native-camera', :path => '../node_modules/react-native-camera'

end

