
const prefix = (label) => `redpine/app/services/shows/${label}`

const constants = {
	IS_LOADING_ARTIST_SHOWS: prefix('IS_LOADING_ARTIST_SHOWS'),
	SET_ARTIST_SHOWS: prefix('SET_ARTIST_SHOWS'),
	SET_ARTIST_SHOWS_ERROR: prefix('SET_ARTIST_SHOWS_ERROR'),

	IS_LOADING_VENUE_PENDING_SHOWS: prefix('IS_LOADING_VENUE_PENDING_SHOWS'),
	SET_VENUE_PENDING_SHOWS: prefix('SET_VENUE_PENDING_SHOWS'),
	SET_VENUE_PENDING_SHOWS_ERROR: prefix('SET_VENUE_PENDING_SHOWS_ERROR'),

	SET_UPDATE_CAMPAIGN_BAND_PENDING: prefix('SET_UPDATE_CAMPAIGN_BAND_PENDING'),
	SET_UPDATE_VENUE_INVITATION_PENDING: prefix('SET_UPDATE_VENUE_INVITATION_PENDING'),
}

export default constants